### ISSUE TITLE
Failed loading language 'tha'

### ISSUE THREAD

**Issue by kmusicman** [jeromewu/tesseract.js-offline#1]
Hi @jeromewu 
I clone tesseract.js-offline for thai language but return error Failed loading language 'tha'.
I put a tha.traineddata.gz file in /lang-data  

Test on http://localhost:3000/browser/

console log error.
- Error opening data file ./tha.traineddata
- Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
- Failed loading language 'tha'
- Tesseract couldn't load any languages!

Thank you.

**Comment by jeromewu** [comment]
The issue has been fixed in the latest version, please check the latest code.
Don't forget to upgrade tesseract.js to v2.0.0-alpha.11.

**Comment by kmusicman** [comment]
@jeromewu Thank you.
